insert into auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at,
  is_anonymous
) values
(
  '00000000-0000-0000-0000-000000000000',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'authenticated',
  'authenticated',
  'tengchuanheji@gmail.com',
  null,
  '2026-01-22 08:52:57.44943+00',
  null,
  '',
  null,
  '',
  null,
  '',
  '',
  null,
  '2026-01-22 11:30:32.726329+00',
  '{"provider": "google", "providers": ["google"]}',
  '{"iss": "https://accounts.google.com", "sub": "113063214262650760898", "name": "Kazuki Fujikawa", "email": "tengchuanheji@gmail.com", "picture": "https://lh3.googleusercontent.com/a/ACg8ocJc0xmTuRqRwHl6icu5D494q3oOw0tw3wsXe70B2sbM92CJYxw0=s96-c", "full_name": "Kazuki Fujikawa", "avatar_url": "https://lh3.googleusercontent.com/a/ACg8ocJc0xmTuRqRwHl6icu5D494q3oOw0tw3wsXe70B2sbM92CJYxw0=s96-c", "provider_id": "113063214262650760898", "email_verified": true, "phone_verified": false}',
  null,
  '2026-01-22 08:52:57.438833+00',
  '2026-01-23 02:01:03.249488+00',
  null,
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null,
  false
)
on conflict (id) do nothing;

insert into auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at,
  is_anonymous
) values
(
  '00000000-0000-0000-0000-000000000000',
  '7c1d4e2e-5f6a-4b7e-8f2c-6f2d1b2a3c4d',
  'authenticated',
  'authenticated',
  'yuto@example.com',
  null,
  now() - interval '7 days',
  null,
  '',
  null,
  '',
  null,
  '',
  '',
  null,
  now() - interval '1 day',
  '{"provider": "google", "providers": ["google"]}',
  '{"name": "Yuto Aoki", "email": "yuto@example.com", "full_name": "Yuto Aoki", "avatar_url": ""}',
  null,
  now() - interval '7 days',
  now() - interval '1 day',
  null,
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null,
  false
),
(
  '00000000-0000-0000-0000-000000000000',
  '9a3c2b1d-4e5f-6a7b-8c9d-0e1f2a3b4c5d',
  'authenticated',
  'authenticated',
  'rin@example.com',
  null,
  now() - interval '10 days',
  null,
  '',
  null,
  '',
  null,
  '',
  '',
  null,
  now() - interval '2 days',
  '{"provider": "google", "providers": ["google"]}',
  '{"name": "Rin Nakata", "email": "rin@example.com", "full_name": "Rin Nakata", "avatar_url": ""}',
  null,
  now() - interval '10 days',
  now() - interval '2 days',
  null,
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null,
  false
),
(
  '00000000-0000-0000-0000-000000000000',
  '2b4c6d8e-1f3a-5b7c-9d0e-1f2a3b4c5d6e',
  'authenticated',
  'authenticated',
  'haru@example.com',
  null,
  now() - interval '14 days',
  null,
  '',
  null,
  '',
  null,
  '',
  '',
  null,
  now() - interval '3 days',
  '{"provider": "google", "providers": ["google"]}',
  '{"name": "Haru Sato", "email": "haru@example.com", "full_name": "Haru Sato", "avatar_url": ""}',
  null,
  now() - interval '14 days',
  now() - interval '3 days',
  null,
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null,
  false
)
on conflict (id) do nothing;
