insert into public.tricks (
  id,
  user_id,
  type,
  custom_name,
  stance,
  takeoff,
  axis,
  spin,
  grab,
  direction,
  is_public,
  created_at,
  updated_at
) values
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'air',
  null,
  'regular',
  'carving',
  '平軸',
  540,
  'ミュート',
  'left',
  true,
  now(),
  now()
),
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'air',
  null,
  'regular',
  'standard',
  'コーク',
  720,
  'セーフティ',
  'right',
  false,
  now() - interval '1 day',
  now() - interval '1 day'
),
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'air',
  null,
  'switchStance',
  'standard',
  '平軸',
  540,
  'ジャパン',
  'left',
  true,
  now() - interval '3 days',
  now() - interval '3 days'
),
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'jib',
  '270オン 270オフ',
  null,
  null,
  null,
  null,
  null,
  null,
  true,
  now() - interval '2 days',
  now() - interval '2 days'
),
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'jib',
  'フロント450アウト',
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  now() - interval '4 days',
  now() - interval '4 days'
)
on conflict (id) do nothing;
