insert into public.tricks (
  id,
  user_id,
  type,
  custom_name,
  stance,
  takeoff,
  axis,
  spin,
  grab,
  direction,
  is_public,
  created_at,
  updated_at
) values
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'air',
  null,
  'regular',
  'carving',
  'upright',
  540,
  'mute',
  'left',
  true,
  now(),
  now()
),
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'air',
  null,
  'regular',
  'straight',
  'cork',
  720,
  'safety',
  'right',
  false,
  now() - interval '1 day',
  now() - interval '1 day'
),
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'air',
  null,
  'switchStance',
  'straight',
  'upright',
  540,
  'japan',
  'left',
  true,
  now() - interval '3 days',
  now() - interval '3 days'
),
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'jib',
  '270オン 270オフ',
  null,
  null,
  null,
  null,
  null,
  null,
  true,
  now() - interval '2 days',
  now() - interval '2 days'
),
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2',
  '38df4b07-e015-4d61-ab23-c65bf9d835c8',
  'jib',
  'フロント450アウト',
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  now() - interval '4 days',
  now() - interval '4 days'
)
on conflict (id) do nothing;

insert into public.tricks (
  id,
  user_id,
  type,
  custom_name,
  stance,
  takeoff,
  axis,
  spin,
  grab,
  direction,
  is_public,
  created_at,
  updated_at
) values
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4',
  '7c1d4e2e-5f6a-4b7e-8f2c-6f2d1b2a3c4d',
  'air',
  null,
  'regular',
  'carving',
  'doubleCork',
  1080,
  'mute',
  'left',
  true,
  now() - interval '6 days',
  now() - interval '6 days'
),
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3',
  '7c1d4e2e-5f6a-4b7e-8f2c-6f2d1b2a3c4d',
  'jib',
  'フロント270オン 450オフ',
  null,
  null,
  null,
  null,
  null,
  null,
  true,
  now() - interval '5 days',
  now() - interval '5 days'
),
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5',
  '9a3c2b1d-4e5f-6a7b-8c9d-0e1f2a3b4c5d',
  'air',
  null,
  'switchStance',
  'straight',
  'cork',
  720,
  'japan',
  'right',
  true,
  now() - interval '9 days',
  now() - interval '9 days'
),
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4',
  '9a3c2b1d-4e5f-6a7b-8c9d-0e1f2a3b4c5d',
  'jib',
  'スイッチテールプレス 270オフ',
  null,
  null,
  null,
  null,
  null,
  null,
  true,
  now() - interval '8 days',
  now() - interval '8 days'
),
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6',
  '2b4c6d8e-1f3a-5b7c-9d0e-1f2a3b4c5d6e',
  'air',
  null,
  'regular',
  'straight',
  'upright',
  900,
  'safety',
  'left',
  true,
  now() - interval '12 days',
  now() - interval '12 days'
),
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5',
  '2b4c6d8e-1f3a-5b7c-9d0e-1f2a3b4c5d6e',
  'jib',
  'スイッチノーズプレス 360オフ',
  null,
  null,
  null,
  null,
  null,
  null,
  true,
  now() - interval '11 days',
  now() - interval '11 days'
)
on conflict (id) do nothing;
